"use client";

import {Raleway} from "next/font/google"
import "./globals.css";
import Image from "next/image";
import Link from "next/link";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faBars } from '@fortawesome/free-solid-svg-icons'
import { usePathname } from "next/navigation";
import { useEffect, useState } from "react";

const raleway = Raleway({
  subsets:['latin']
})

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const currentPath = usePathname();

  const [isMenuOpen, setIsMenuOpen] = useState(false);

  useEffect(() => {
    setIsMenuOpen(false);
  }, [currentPath]);

  return (
    <html lang="en">
      <body
        className={`${raleway.className} antialiased`}
      >
         {/* <!-- Navbar Start --> */}
        <div className="w-full h-[70px] bg-[#800B35] flex items-center gap-3 px-3 md:px-20">
            <div className="flex items-center">
              <Image src={"/img/logo.jpeg"} width={50} height={49} alt="logo" />
            </div>
            <div className="leading-5 pt-2">
                <h1 className="text-white font-[650] text-[25px] text-center" style={{ textShadow: "1px 2px 2px #959595" }}>PT. Creative Branding Indonesia</h1>
                <h2 className="text-white text-[13px] text-center">Fragrances - Flavours - Ingredients</h2>
            </div>
        </div>
        {/* <!-- Navbar End --> */}
        
        {/* <!-- Jumbotron Image --> */}
        <div>
          <Image src={"/img/switfy.jpg"} width={1349} height={400} className="w-full" alt="jumbotron" />
        </div>
        {/* <!-- Jumbotron End --> */}
        
        {/* <!-- Links Start --> */}
        <div className="w-full bg-[#AF0F48] hidden md:flex px-20"> {/* md:grid md:grid-cols-3 */}
            <ul>
                <li className="float-left">
                    <div className="group">
                        <Link href="/">
                            <div className={`p-[1.4rem] ${currentPath == "/" ? "bg-[#800B35]" : "hover:bg-[#800B35]" } `}>
                                <div>
                                    <p className="text-white text-[17px]">Home</p>
                                </div>
                            </div>
                        </Link>
                        <div className="hidden group-hover:block bg-[#AF0F48] text-white list-none absolute mr-20 shadow-md">
                            <ul>
                                <Link href="/">
                                    <li className={`py-[0.9rem] px-14 ${currentPath == "/" ? "bg-[#800B35]" : "hover:bg-[#800B35]" }`}>
                                        <p>Home</p>
                                    </li>
                                </Link>
                                <Link href="/who-are-we">
                                    <li className={`py-[0.9rem] px-14 ${currentPath == "/who-are-we" ? "bg-[#800B35]" : "hover:bg-[#800B35]" }`}>
                                        <p>Who are we?</p>
                                    </li>
                                </Link>
                                <Link href="/siapa-kami">
                                    <li className={`py-[0.9rem] px-14 ${currentPath == "/siapa-kami" ? "bg-[#800B35]" : "hover:bg-[#800B35]" }`}>
                                        <p>Siapa kami</p>
                                    </li>
                                </Link>
                            </ul>
                        </div>
                    </div>
                </li>
                <li className="float-left">
                    <Link href="/fragrances">
                        <div className={`p-[1.4rem] ${currentPath == "/fragrances" ? "bg-[#800B35]" : "hover:bg-[#800B35]" }`}>
                            <p className="text-white text-[17px]">Fragrances</p>
                        </div>
                    </Link>
                </li>
                <li className="float-left">
                    <Link href="/wewangian">
                        <div className={`p-[1.4rem] ${currentPath == "/wewangian" ? "bg-[#800B35]" : "hover:bg-[#800B35]" }`}>
                            <p className="text-white text-[17px]">Wewangian</p>
                        </div>
                    </Link>
                </li>
                <li className="float-left">
                    <Link href="/contact">
                        <div className={`p-[1.4rem] ${currentPath == "/contact" ? "bg-[#800B35]" : "hover:bg-[#800B35]" }`}>
                            <p className="text-white text-[17px]">Contact/Kontakt</p>
                        </div>
                    </Link>
                </li>
                <li className="float-left">
                    <Link href="/flavours">
                        <div className={`p-[1.4rem] ${currentPath == "/flavours" ? "bg-[#800B35]" : "hover:bg-[#800B35]" }`}>
                            <p className="text-white text-[17px]">Perencah/Flavours</p>
                        </div>
                    </Link>
                </li>
                <li className="float-left">
                    <Link href="/ingredients">
                        <div className={`p-[1.4rem] ${currentPath == "/ingredients" ? "bg-[#800B35]" : "hover:bg-[#800B35]" }`}>
                            <p className="text-white text-[17px]">Ingredients</p>
                        </div>
                    </Link>
                </li>
                <li className="float-left">
                    <Link href="/tailored-service">
                        <div className={`p-[1.4rem] ${currentPath == "/tailored-service" ? "bg-[#800B35]" : "hover:bg-[#800B35]" }`}>
                            <p className="text-white text-[17px]">Tailored Service</p>
                        </div>
                    </Link>
                </li>
            </ul>
        </div>
        {/* ⬇ Mobile ⬇ */}
        <div className="w-full bg-[#AF0F48] block md:hidden">
          <input type="checkbox" id="openNav" className="hidden peer" checked={isMenuOpen}/>
          <label htmlFor="openNav" onClick={() => {setIsMenuOpen(!isMenuOpen)}}>
            <div className="flex text-center w-full justify-center hover:cursor-pointer"> 
              <FontAwesomeIcon icon={faBars} className="text-white size-10" />
            </div>
          </label>
          <div className="hidden peer-checked:block">
            <Link href="/">
                <div className={`p-[1.4rem] ${currentPath == "/" ? "bg-[#800B35]" : "hover:bg-[#800B35]" }`}>
                    <div>
                        <p className="text-white text-[17px]">Home</p>
                    </div>
                </div>
            </Link>
            <Link href="/">
                <div className={`p-[1.4rem] ${currentPath == "/" ? "bg-[#800B35]" : "hover:bg-[#800B35]" }`}>
                    <div>
                        <p className="text-white text-[13.6px] ml-5">Home</p>
                    </div>
                </div>
            </Link>
            <Link href="/who-are-we">
                <div className={`p-[1.4rem] ${currentPath == "/who-are-we" ? "bg-[#800B35]" : "hover:bg-[#800B35]" }`}>
                    <div>
                        <p className="text-white text-[13.6px] ml-5">Who are we?</p>
                    </div>
                </div>
            </Link>
            <Link href="/siapa-kami">
                <div className={`p-[1.4rem] ${currentPath == "/siapa-kami" ? "bg-[#800B35]" : "hover:bg-[#800B35]" }`}>
                    <div>
                        <p className="text-white text-[13.6px] ml-5">Siapa Kami?</p>
                    </div>
                </div>
            </Link>
            <Link className="min-w-full" href="/fragrances">
                <p className={`text-white text-[17px] p-5 ${currentPath == "/fragrances" ? "bg-[#800B35]" : "hover:bg-[#800B35]" }`}>Fragrances</p>
            </Link>
            <Link className="min-w-full" href="/wewangian">
                <p className={`text-white text-[17px] p-5 ${currentPath == "/wewangian" ? "bg-[#800B35]" : "hover:bg-[#800B35]" }`}>Wewangian</p>
            </Link>
            <Link className="min-w-full" href="/contact">
                <p className={`text-white text-[17px] p-5 ${currentPath == "/contact" ? "bg-[#800B35]" : "hover:bg-[#800B35]" }`}>Contact/Kontakt</p>
            </Link>
            <Link className="min-w-full" href="/flavours">
                <p className={`text-white text-[17px] p-5 ${currentPath == "/flavours" ? "bg-[#800B35]" : "hover:bg-[#800B35]" }`}>Perencah/Flavours</p>
            </Link>
            <Link className="w-full" href="/ingredients">
                <p className={`text-white text-[17px] p-5 ${currentPath == "/ingredients" ? "bg-[#800B35]" : "hover:bg-[#800B35]" }`}>Ingredients</p>
            </Link>
            <Link className="w-full" href="/tailored-service">
                <p className={`text-white text-[17px] p-5 ${currentPath == "/tailored-service" ? "bg-[#800B35]" : "hover:bg-[#800B35]" }`}>Tailored Service</p>
            </Link>
          </div>
        </div>

        <div className="w-full bg-[#800B35] p-[0.15rem]"></div>
        {/* <!-- Links End --> */}

        {/* <!-- Body Start --> */}
        <div>
            <div className="px-5 lg:px-20 py-5 flex">
                <div className="bg-[#800B35] hidden lg:block lg:min-h-screen lg:w-[22%]"></div>
                {children}
            </div>
        </div>
        {/* <!-- Body End --> */}

        {/* <!-- Footer Start --> */}
        <div className="bg-[#424242] min-w-full h-48"></div>
        {/* <!-- Footer End --> */}
      </body>
    </html>
  );
}
